### ISSUE TITLE
我想问下如何将Binding的数据进行翻译

### ISSUE THREAD

**Issue by GQ-zhang** [LorisYounger/LinePutScript.Localization.WPF#1]
是否可以再例子中进行展现

**Comment by LorisYounger** [comment]
`LinePutScript.Localization.WPF`支持通过binding的方式进行数据翻译
在 XAML 中使用这个 StrExtension 的方式如下：
```xml
<Run Text="{ll:Str {Binding YourProperty}}" />
```
这个是 翻译组件 https://github.com/LorisYounger/LinePutScript.Localization.WPF 的问题, 和LPS无关
之前通过邮件回复了,不过消息被吞了,最近才看到
